# Generated by Django 3.2.7 on 2021-09-07 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20210906_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='photo',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
