# Generated by Django 3.2.7 on 2021-09-08 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_item_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='stripe_id',
        ),
    ]
