# Generated by Django 3.2.7 on 2021-09-21 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_payment_stripe_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment',
        ),
    ]
